[application]

# App (Project) Name
name = "persian-tools-web"

# Dioxus App Default Platform
# desktop, web
default_platform = "web"

# `build` & `serve` dist path
out_dir = "docs"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "persian-tools-web"

# github path is https://ali77gh.github.io/PersianToolsWeb/ so:
base_path = "PersianToolsWeb"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = ["/PersianToolsWeb/tailwind.css","/PersianToolsWeb/main.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
